// <auto-generated />
using System;
using InventoryManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522025800_AddUniqueIndexToClienteFornecedorNome")]
    partial class AddUniqueIndexToClienteFornecedorNome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("InventoryManagerApi.Models.ClienteFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ClientesFornecedores");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FatorConversao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoUnidadeVendaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoUnidadeVendaId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteFornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFornecedorId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MenorUnidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadeMedidaCompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenorUnidadeId");

                    b.HasIndex("UnidadeMedidaCompraId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.ProdutoUnidadeVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FatorConversao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MenorUnidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoPadrao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenorUnidadeId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("ProdutosUnidadeVenda");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.ItemPedido", b =>
                {
                    b.HasOne("InventoryManagerApi.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.ProdutoUnidadeVenda", "ProdutoUnidadeVenda")
                        .WithMany()
                        .HasForeignKey("ProdutoUnidadeVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoUnidadeVenda");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("InventoryManagerApi.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Pedido", b =>
                {
                    b.HasOne("InventoryManagerApi.Models.ClienteFornecedor", "ClienteFornecedor")
                        .WithMany()
                        .HasForeignKey("ClienteFornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteFornecedor");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Produto", b =>
                {
                    b.HasOne("InventoryManagerApi.Models.UnidadeMedida", "MenorUnidade")
                        .WithMany("ProdutosMenorUnidade")
                        .HasForeignKey("MenorUnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.UnidadeMedida", "UnidadeMedidaCompra")
                        .WithMany("ProdutosCompra")
                        .HasForeignKey("UnidadeMedidaCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenorUnidade");

                    b.Navigation("UnidadeMedidaCompra");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.ProdutoUnidadeVenda", b =>
                {
                    b.HasOne("InventoryManagerApi.Models.UnidadeMedida", "MenorUnidade")
                        .WithMany()
                        .HasForeignKey("MenorUnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.Produto", "Produto")
                        .WithMany("UnidadesVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagerApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany("ProdutosVenda")
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenorUnidade");

                    b.Navigation("Produto");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.Produto", b =>
                {
                    b.Navigation("UnidadesVenda");
                });

            modelBuilder.Entity("InventoryManagerApi.Models.UnidadeMedida", b =>
                {
                    b.Navigation("ProdutosCompra");

                    b.Navigation("ProdutosMenorUnidade");

                    b.Navigation("ProdutosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
